name: ci/integration-tests

on:
  workflow_run:
    workflows: [ "ci/unit-tests" ]
    types: [ completed ]
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    name: integration tests
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Create .env
        run: |
          if [ -f .env.example ]; then cp .env.example .env; fi

      - name: Run integration tests
        run: make test-integration

